In [3]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [5]:
np.random.random((3,3,3))

array([[[0.26718247, 0.23218767, 0.69266438],
        [0.79715212, 0.47867417, 0.68977429],
        [0.05419011, 0.91375827, 0.77246823]],

       [[0.51060531, 0.88640347, 0.89957032],
        [0.49487412, 0.57663347, 0.72671473],
        [0.5958612 , 0.10813048, 0.47034325]],

       [[0.27243415, 0.36935996, 0.25491733],
        [0.96936044, 0.80518601, 0.06422798],
        [0.67064864, 0.61674109, 0.26690026]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
np.tril([1,2,3,4])

array([[1, 0, 0, 0],
       [1, 2, 0, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 4]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [23]:
arr=np.zeros((8,8))
arr[1::2, ::2]=1
arr[::2,1::2]=1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [12]:
arr=np.random.randint(0,100,(5,5))
print("original array\n",arr)
arrmax,arrmin=arr.max(),arr.min()
print("normalised array\n",(arr-arrmin)/(arrmax-arrmin))

original array
 [[26 99 68 29 29]
 [45 26 17 50 74]
 [86  0 39 92 81]
 [96 28 13 39 32]
 [58 71 89 56 32]]
normalised array
 [[0.26262626 1.         0.68686869 0.29292929 0.29292929]
 [0.45454545 0.26262626 0.17171717 0.50505051 0.74747475]
 [0.86868687 0.         0.39393939 0.92929293 0.81818182]
 [0.96969697 0.28282828 0.13131313 0.39393939 0.32323232]
 [0.58585859 0.71717172 0.8989899  0.56565657 0.32323232]]


# 5.  How to find common values between two arrays?

In [6]:
a=np.array([1,2,3,4])
b=np.array([3,4,9,5,6,7])
np.intersect1d(a,b)


array([3, 4])

# 6.How to get the dates of yesterday, today and tomorrow?

In [41]:
yesterday= np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday:",yesterday)
today= np.datetime64('today', 'D')
print("Today:",today)
tomorrow= np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow:",tomorrow)

Yestraday: 2020-07-26
Today: 2020-07-27
Tomorrow: 2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [9]:
a= np.random.randint(0,10,6)
print("First array:",a)
b= np.random.randint(0,10,6)
print("Second array:",b)
array_equal = np.allclose(a,b)
print(array_equal)

First array: [5 7 3 4 5 1]
Second array: [2 0 9 8 8 7]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [23]:
a= np.random.randint(100,size=(10))
print("original array",a)
a[a.argmax()]=0
print("new array",a)


original array [41 51 55 82 89 19 58 23 68 22]
new array [41 51 55 82  0 19 58 23 68 22]


# 9. How to print all the values of an array?

In [26]:
a=np.arange(12).reshape(3,4)
np.set_printoptions(threshold=np.nan)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# 10.Subtract the mean of each row of a matrix

In [45]:
x = np.random.randint(0,100, (5,5))
print(x)
print("Subtract the mean of each row of the matrix:\n")
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[61  9  5 59 35]
 [44 64 72 80  1]
 [42 35 14 51 43]
 [98  0 28 47 55]
 [15 57  1 50 81]]
Subtract the mean of each row of the matrix:

[[ 27.2 -24.8 -28.8  25.2   1.2]
 [ -8.2  11.8  19.8  27.8 -51.2]
 [  5.   -2.  -23.   14.    6. ]
 [ 52.4 -45.6 -17.6   1.4   9.4]
 [-25.8  16.2 -39.8   9.2  40.2]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [10]:
v1 = np.random.randint(0,100,20)
print(v1)
v2 = np.random.randint(0,len(v1),20)
print(v2)
v1 += np.bincount(v2, minlength=len(v1))
print(v1)

[12  6 39 26 23 99 97 48 66 45 45 68  5 89 23 14 30 40 64 16]
[ 5  1 14 17  2 10  9 17  8  9  3 15  7 10  1 12  9  8  4  9]
[ 12   8  40  27  24 100  97  49  68  49  47  68   6  89  24  15  30  42
  64  16]


# 12.How to get the diagonal of a dot product?

In [29]:
arr=np.random.randint(0,100,(5,5))
arr2=np.random.randint(0,100,(5,5))
arr3=np.dot(arr,arr2)
np.diag(arr3,k=0)

array([ 9367,  7316, 11857,  8290, 19873])

# 13.How to find the most frequent value in an array?

In [30]:
arr4=np.random.randint(0,100,50)
print("most frequent value",np.bincount(arr4).argmax())

most frequent value 87


# 14.How to get the n largest values of an array

In [35]:
arr5= np.arange(40)
np.random.shuffle(arr5)
print("Original array:")
print(arr5)
n=int(input("enter value of n"))
print(arr5[np.argsort(arr5)[-n:]])

Original array:
[37 31 21  2 25  6 16  5 11  0 18  7 24 26 27 35 23 34 15  9 36 14 32  3
 39 22 10  8 38 12 30 28 29 13 19 17 20  1 33  4]
enter value of n5
[35 36 37 38 39]


# 15.How to create a record array from a regular array?

In [46]:
arra1 = np.array([(101,"Tarun sharma ", 88.5),(102,"Anyaa Tripathi", 81),(103,"Diljeet Singh", 91)])
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'i8,S80,f8')
print(result)

[(101, b'Tarun sharma ', 88.5) (102, b'Anyaa Tripathi', 81. )
 (103, b'Diljeet Singh', 91. )]
